# Generated by Django 4.0 on 2022-01-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=2000)),
            ],
        ),
    ]
