# Generated by Django 4.0 on 2022-01-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addrev',
            fields=[
                ('anime_id', models.AutoField(primary_key=True, serialize=False)),
                ('anime_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=2000)),
                ('anime_img', models.ImageField(default='', upload_to='animes/images')),
                ('noOfRev', models.IntegerField(default=1)),
            ],
        ),
    ]
