# Generated by Django 4.0 on 2022-01-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seriesrev',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('series_name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('series_img', models.ImageField(default='', upload_to='series/images')),
            ],
        ),
    ]
