# Generated by Django 4.0 on 2022-01-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesrev',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='seriesrev',
            name='rating',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
