# Generated by Django 4.0 on 2022-01-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_seriesrev_desc_seriesrev_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesrev',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
