# Generated by Django 4.0 on 2022-01-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_alter_seriesrev_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='myrev',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
