# Generated by Django 4.0 on 2022-01-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_myrev_series_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesrev',
            name='noOfRev',
            field=models.IntegerField(default=1),
        ),
    ]
