# Generated by Django 4.0 on 2022-01-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesrev',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
    ]
