# Generated by Django 4.0 on 2022-01-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0008_seriesrev_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='seriesrev',
            name='desc',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
